version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest # or ghcr.io/ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - backend
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3003:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    networks:
      - backend
    restart: unless-stopped

volumes:
  ollama:

networks:
  backend:
    driver: bridge
